### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by varsis** [CMPUT301F13T05/Team05_CYOA#5]
Describe, using detailed textual use cases, the tasks for completing each type of entry. For each user story in the project description, add a reasonable set of verifying tests. For easier reference (such as in planning), number the use cases and user stories. This information will likely evolve and should be maintained up-to-date in your team wiki. A "surprise" change will be introduced after project part 2.

**Comment by klafond** [comment]
This is also assigned to ULVI Joel is doing 1-8 Ulvi is doing 9-16
